Repository Agnieszka1990/esp8266-micropython-weather-logger, pull requests merged in 2019-07, with the labels that each got.

#5 added current time logging
  main.py
Labels: enhancement

#6 update http server
  main.py
Labels: update

#7 Added usage of time in http logging
  main.py
Labels: enhancement

#11 fix for wrong timezone offset
  main.py
Labels: bugfix

#12 update server
  main.py
Labels: update
